// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.App.Persistencia;

namespace Sistema.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Sistema.App.Dominio.DesempenoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GolEnContra")
                        .HasColumnType("int");

                    b.Property<int>("GolFavor")
                        .HasColumnType("int");

                    b.Property<int>("PartidoEmpatado")
                        .HasColumnType("int");

                    b.Property<int>("PartidoGanado")
                        .HasColumnType("int");

                    b.Property<int>("PartidoJugado")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<int?>("ResultadoPartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoPartidoId");

                    b.ToTable("Desempenos");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DtId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DtId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Sistema.App.Dominio.EstadisticaPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amarilla")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gol")
                        .HasColumnType("int");

                    b.Property<int>("Marcador")
                        .HasColumnType("int");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoJugadoId")
                        .HasColumnType("int");

                    b.Property<int>("Roja")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoJugadoId");

                    b.ToTable("EstadisticasPartidos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EstadisticaPartido");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<int?>("CanchaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocalId")
                        .HasColumnType("int");

                    b.Property<int?>("VisitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("LocalId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("Sistema.App.Dominio.StatsVisitante", b =>
                {
                    b.HasBaseType("Sistema.App.Dominio.EstadisticaPartido");

                    b.HasDiscriminator().HasValue("StatsVisitante");
                });

            modelBuilder.Entity("Sistema.App.Dominio.statsLocal", b =>
                {
                    b.HasBaseType("Sistema.App.Dominio.EstadisticaPartido");

                    b.HasDiscriminator().HasValue("statsLocal");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Arbitro", b =>
                {
                    b.HasBaseType("Sistema.App.Dominio.Persona");

                    b.Property<string>("Escuela")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Arbitro");
                });

            modelBuilder.Entity("Sistema.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasBaseType("Sistema.App.Dominio.Persona");

                    b.HasDiscriminator().HasValue("DirectorTecnico");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Futbolista", b =>
                {
                    b.HasBaseType("Sistema.App.Dominio.Persona");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("PosicionCancha")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EquipoId");

                    b.HasDiscriminator().HasValue("Futbolista");
                });

            modelBuilder.Entity("Sistema.App.Dominio.DesempenoEquipo", b =>
                {
                    b.HasOne("Sistema.App.Dominio.EstadisticaPartido", "ResultadoPartido")
                        .WithMany()
                        .HasForeignKey("ResultadoPartidoId");

                    b.Navigation("ResultadoPartido");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Equipo", b =>
                {
                    b.HasOne("Sistema.App.Dominio.DirectorTecnico", "Dt")
                        .WithMany()
                        .HasForeignKey("DtId");

                    b.HasOne("Sistema.App.Dominio.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.HasOne("Sistema.App.Dominio.Torneo", null)
                        .WithMany("Participante")
                        .HasForeignKey("TorneoId");

                    b.Navigation("Dt");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Estadio", b =>
                {
                    b.HasOne("Sistema.App.Dominio.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Sistema.App.Dominio.EstadisticaPartido", b =>
                {
                    b.HasOne("Sistema.App.Dominio.Partido", "PartidoJugado")
                        .WithMany()
                        .HasForeignKey("PartidoJugadoId");

                    b.Navigation("PartidoJugado");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Partido", b =>
                {
                    b.HasOne("Sistema.App.Dominio.Arbitro", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId");

                    b.HasOne("Sistema.App.Dominio.Estadio", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId");

                    b.HasOne("Sistema.App.Dominio.Equipo", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.HasOne("Sistema.App.Dominio.Equipo", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId");

                    b.Navigation("Arbitro");

                    b.Navigation("Cancha");

                    b.Navigation("Local");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Futbolista", b =>
                {
                    b.HasOne("Sistema.App.Dominio.Equipo", null)
                        .WithMany("Plantilla")
                        .HasForeignKey("EquipoId");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Equipo", b =>
                {
                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("Sistema.App.Dominio.Torneo", b =>
                {
                    b.Navigation("Participante");
                });
#pragma warning restore 612, 618
        }
    }
}
